// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News_Asp_Net_Api.Data;

#nullable disable

namespace News_Asp_Net_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContextApp))]
    partial class ApplicationDbContextAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("News_Asp_Net_Api.Models.kategori_ara", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("kategori_Id")
                        .HasColumnType("int");

                    b.Property<int>("news_Id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("kategori_ara");
                });

            modelBuilder.Entity("News_Asp_Net_Api.Models.kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("kategoriAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("kategoriler");
                });

            modelBuilder.Entity("News_Asp_Net_Api.Models.kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("kullaniciAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("kullanicininAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("News_Asp_Net_Api.Models.news", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("newsCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("newsDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("newsTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("news");
                });
#pragma warning restore 612, 618
        }
    }
}
